name: Build and push Docker image to Docker Hub
on:
  workflow_dispatch:
    inputs:
      docker_image_tag:
        description: 'Docker image tag'
        required: true
  push:
    tags:
      - mockserver-*

jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get tag name
        id: get_docker_image_tag
        shell: bash
        run: |
          if [ "$DOCKER_TAG" == "" ]; then
            echo "::set-output name=docker_image_tag::${GITHUB_REF/refs\/tags\//}"
          else
            echo "::set-output name=docker_image_tag::${DOCKER_TAG}"
          fi
        env:
          DOCKER_TAG: ${{ github.event.inputs.docker_image_tag }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: docker/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: mockserver/mockserver:${{ steps.get_docker_image_tag.outputs.docker_image_tag }}
